In [28]:
import pandas as pd
from sklearn import linear_model

df = pd.read_csv('data/data.csv')
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [29]:
X = df[['Weight', 'Volume']]
y = df['CO2']

In [31]:
X.head()

   Weight  Volume
0     790    1000
1    1160    1200
2     929    1000
3     865     900
4    1140    1500

In [33]:
y.head()

0     99
1     95
2     95
3     90
4    105
Name: CO2, dtype: int64

In [34]:
regr = linear_model.LinearRegression()
regr.fit(X, y)

predictedCO2 = regr.predict([[2300, 1300]]) # 2300 kg, 1300 CM3
print(predictedCO2)

[107.2087328]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [25]:
#Coefficient
#Example: if x is a variable, then 2x is x two times. x is the unknown variable, and the number 2 is the coefficient.

In [26]:
import pandas
from sklearn import linear_model

df = pandas.read_csv("data/data.csv")

X = df[['Weight', 'Volume']]
y = df['CO2']

regr = linear_model.LinearRegression()
regr.fit(X, y)

print(regr.coef_)

[0.00755095 0.00780526]

In [35]:
predictedCO2 = regr.predict([[3300, 1300]]) # 3300 kg, 1300 Cubic meters
print(predictedCO2)

[114.75968007]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [37]:
z = 107.2087328 + 0.00755095 * 1000 
print(z)

114.75968280000001

In [39]:
predictedCO2 = regr.predict([[2300, 2300]]) # 2300 kg, 2300 Cubic meters
print(predictedCO2)

[115.01399033]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [40]:
z = 107.2087328 + 0.00780526 * 1000
print(z)

115.01399280000001

In [42]:
df = pd.read_csv('data/data_scale.csv')
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo     1.0     790   99
1  Mitsubishi  Space Star     1.2    1160   95
2       Skoda      Citigo     1.0     929   95
3        Fiat         500     0.9     865   90
4        Mini      Cooper     1.5    1140  105

In [ ]:
# Scale the data