In [28]:
import pandas as pd
from sklearn import linear_model

df = pd.read_csv('data/data.csv')
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [29]:
X = df[['Weight', 'Volume']]
y = df['CO2']

In [31]:
X.head()

   Weight  Volume
0     790    1000
1    1160    1200
2     929    1000
3     865     900
4    1140    1500

In [33]:
y.head()

0     99
1     95
2     95
3     90
4    105
Name: CO2, dtype: int64

In [34]:
regr = linear_model.LinearRegression()
regr.fit(X, y)

predictedCO2 = regr.predict([[2300, 1300]]) # 2300 kg, 1300 CM3
print(predictedCO2)

[107.2087328]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [25]:
#Coefficient
#Example: if x is a variable, then 2x is x two times. x is the unknown variable, and the number 2 is the coefficient.

In [26]:
import pandas
from sklearn import linear_model

df = pandas.read_csv("data/data.csv")

X = df[['Weight', 'Volume']]
y = df['CO2']

regr = linear_model.LinearRegression()
regr.fit(X, y)

print(regr.coef_)

[0.00755095 0.00780526]

In [35]:
predictedCO2 = regr.predict([[3300, 1300]]) # 3300 kg, 1300 Cubic meters
print(predictedCO2)

[114.75968007]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [37]:
z = 107.2087328 + 0.00755095 * 1000 
print(z)

114.75968280000001

In [39]:
predictedCO2 = regr.predict([[2300, 2300]]) # 2300 kg, 2300 Cubic meters
print(predictedCO2)

[115.01399033]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [40]:
z = 107.2087328 + 0.00780526 * 1000
print(z)

115.01399280000001

In [42]:
df = pd.read_csv('data/data_scale.csv')
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo     1.0     790   99
1  Mitsubishi  Space Star     1.2    1160   95
2       Skoda      Citigo     1.0     929   95
3        Fiat         500     0.9     865   90
4        Mini      Cooper     1.5    1140  105

In [1]:
# Scale the data

In [2]:
import pandas as pd
from sklearn import linear_model
df = pd.read_csv('data/data_scale.csv')
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo     1.0     790   99
1  Mitsubishi  Space Star     1.2    1160   95
2       Skoda      Citigo     1.0     929   95
3        Fiat         500     0.9     865   90
4        Mini      Cooper     1.5    1140  105

In [3]:
# The standardization method uses this formula:
# z = (x - u) / s
# Where z is the new value, x is the original value, u is the mean and s is the standard deviation.
# If you take the weight column from the data set above, the first value is 790, and the scaled value will be:
# (790 - 1292.23) / 238.74 = -2.1
# If you take the volume column from the data set above, the first value is 1.0, and the scaled value will be:
# (1.0 - 1.61) / 0.38 = -1.59
# Now you can compare -2.1 with -1.59 instead of comparing 790 with 1.0.
# You do not have to do this manually, the Python sklearn module has a method called StandardScaler() which returns a Scaler object with methods for transforming data sets.

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
scale = StandardScaler()

X = df[['Weight', 'Volume']]
y = df['CO2']

scaledX = scale.fit_transform(X)
print(scaledX)

[[-2.10389253 -1.59336644]
 [-0.55407235 -1.07190106]
 [-1.52166278 -1.59336644]
 [-1.78973979 -1.85409913]
 [-0.63784641 -0.28970299]
 [-1.52166278 -1.59336644]
 [-0.76769621 -0.55043568]
 [ 0.3046118  -0.28970299]
 [-0.7551301  -0.28970299]
 [-0.59595938 -0.0289703 ]
 [-1.30803892 -1.33263375]
 [-1.26615189 -0.81116837]
 [-0.7551301  -1.59336644]
 [-0.16871166 -0.0289703 ]
 [ 0.14125238 -0.0289703 ]
 [ 0.15800719 -0.0289703 ]
 [ 0.3046118  -0.0289703 ]
 [-0.05142797  1.53542584]
 [-0.72580918 -0.0289703 ]
 [ 0.14962979  1.01396046]
 [ 1.2219378  -0.0289703 ]
 [ 0.5685001   1.01396046]
 [ 0.3046118   1.27469315]
 [ 0.51404696 -0.0289703 ]
 [ 0.51404696  1.01396046]
 [ 0.72348212 -0.28970299]
 [ 0.8281997   1.01396046]
 [ 1.81254495  1.01396046]
 [ 0.96642691 -0.0289703 ]
 [ 1.72877089  1.01396046]
 [ 1.30990057  1.27469315]
 [ 1.90050772  1.01396046]
 [-0.23991961 -0.0289703 ]
 [ 0.40932938 -0.0289703 ]
 [ 0.47215993 -0.0289703 ]
 [ 0.4302729   2.31762392]]

In [9]:
regr = linear_model.LinearRegression()
regr.fit(scaledX, y)

scaled = scale.transform([[2300, 1.3]])
predictedCO2 = regr.predict([scaled[0]])
print(predictedCO2)

[107.2087328]

/Users/jane/Documents/machine-learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(